# Generated by Django 4.1.5 on 2023-01-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('passwd', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='UserRegisteration',
        ),
    ]
