# Generated by Django 4.1.5 on 2023-01-31 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userLog', '0002_member_delete_userregisteration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
