# Generated by Django 4.1.5 on 2023-01-31 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('dateTime', models.DateTimeField()),
                ('num_passenger', models.PositiveBigIntegerField(default=1)),
                ('carType', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Crossover', 'Crossover'), ('Minivan', 'Minivan'), ('Any', 'Any')], default='ANY', max_length=20)),
                ('isShared', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('COMPLETE', 'COMPLETE'), ('COMFIRM', 'COMFIRM')], default='OPEN', max_length=20)),
                ('specialRequest', models.CharField(default=None, max_length=200)),
                ('user', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('carType', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Crossover', 'Crossover'), ('Minivan', 'Minivan')], default='SUV', max_length=20)),
                ('max_passenger', models.PositiveBigIntegerField(default=1)),
                ('license', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
