# Generated by Django 4.1.5 on 2023-02-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequestinfo',
            name='driver',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='riderequestinfo',
            name='driver_fname',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='riderequestinfo',
            name='driver_lname',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='riderequestinfo',
            name='license',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='riderequestinfo',
            name='owner',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='riderequestinfo',
            name='specialRequest',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='riderequestinfo',
            name='status',
            field=models.CharField(choices=[('COMFIRM', 'COMFIRM'), ('OPEN', 'OPEN'), ('COMPLETE', 'COMPLETE')], default='OPEN', max_length=20),
        ),
    ]
