# Generated by Django 4.1.5 on 2023-01-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('dateTime', models.DateTimeField()),
                ('num_passenger', models.PositiveBigIntegerField(default=1)),
                ('carType', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Crossover', 'Crossover'), ('Minivan', 'Minivan'), ('Any', 'Any')], default='ANY', max_length=20)),
                ('isShared', models.BooleanField()),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('COMFIRM', 'COMFIRM'), ('COMPLETE', 'COMPLETE')], default='OPEN', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='max_passenger',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
