# Generated by Django 4.1.5 on 2023-01-31 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverinfo',
            old_name='email',
            new_name='carType',
        ),
    ]
