# Generated by Django 4.1.5 on 2023-02-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequestinfo',
            name='specialRequest',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
