# Generated by Django 4.1.5 on 2023-01-31 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_email_driverinfo_cartype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='carType',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Crossover', 'Crossover'), ('Minivan', 'Minivan')], default='SUV', max_length=20),
        ),
    ]
