# Generated by Django 4.1.5 on 2023-02-02 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_riderequestinfo_driver_riderequestinfo_driver_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequestinfo',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riderequestinfo',
            name='status',
            field=models.CharField(choices=[('COMFIRM', 'COMFIRM'), ('COMPLETE', 'COMPLETE'), ('OPEN', 'OPEN')], default='OPEN', max_length=20),
        ),
    ]
