# Generated by Django 4.1.5 on 2023-02-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_riderequestinfo_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequestinfo',
            name='spotAvaliableLeft',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='riderequestinfo',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('OPEN', 'OPEN'), ('COMFIRM', 'COMFIRM')], default='OPEN', max_length=20),
        ),
    ]
