# Generated by Django 4.1.5 on 2023-02-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_riderequestinfo_driver_alter_riderequestinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequestinfo',
            name='owner',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='riderequestinfo',
            name='status',
            field=models.CharField(choices=[('COMFIRM', 'COMFIRM'), ('COMPLETE', 'COMPLETE'), ('OPEN', 'OPEN')], default='OPEN', max_length=20),
        ),
    ]
