# Generated by Django 4.1.5 on 2023-02-03 01:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_riderequestinfo_sharer_alter_riderequestinfo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderequestinfo',
            name='sharer',
        ),
        migrations.AlterField(
            model_name='riderequestinfo',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('OPEN', 'OPEN'), ('COMFIRM', 'COMFIRM')], default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='riderequestinfo',
            name='sharer',
            field=models.ManyToManyField(related_name='sharer', to=settings.AUTH_USER_MODEL),
        ),
    ]
