# Generated by Django 4.1.5 on 2023-02-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_riderequestinfo_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequestinfo',
            name='owner',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='riderequestinfo',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('COMFIRM', 'COMFIRM'), ('OPEN', 'OPEN')], default='OPEN', max_length=20),
        ),
    ]
