# Generated by Django 4.1.5 on 2023-02-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_riderequestinfo_owner_alter_riderequestinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequestinfo',
            name='driver_fname',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='riderequestinfo',
            name='driver_lname',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='riderequestinfo',
            name='license',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='riderequestinfo',
            name='specialRequest',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='riderequestinfo',
            name='status',
            field=models.CharField(choices=[('COMFIRM', 'COMFIRM'), ('COMPLETE', 'COMPLETE'), ('OPEN', 'OPEN')], default='OPEN', max_length=20),
        ),
    ]
