# Generated by Django 4.1.5 on 2023-02-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_sharerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequestinfo',
            name='status',
            field=models.CharField(choices=[('COMFIRM', 'COMFIRM'), ('OPEN', 'OPEN'), ('COMPLETE', 'COMPLETE')], default='OPEN', max_length=20),
        ),
    ]
