# Generated by Django 4.1.5 on 2023-02-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_riderequestinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='carType',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Crossover', 'Crossover'), ('Minivan', 'Minivan'), ('Any', 'Any')], default='SUV', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderequestinfo',
            name='carType',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Crossover', 'Crossover'), ('Minivan', 'Minivan'), ('Any', 'Any')], default='Any', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderequestinfo',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('COMFIRM', 'COMFIRM'), ('COMPLETE', 'COMPLETE')], default='OPEN', max_length=20),
        ),
    ]
