# Generated by Django 4.1.5 on 2023-02-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_driverinfo_cartype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='carType',
            field=models.CharField(choices=[('Any', 'Any'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Crossover', 'Crossover'), ('Minivan', 'Minivan')], default='Any', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderequestinfo',
            name='carType',
            field=models.CharField(choices=[('Any', 'Any'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Crossover', 'Crossover'), ('Minivan', 'Minivan')], default='Any', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderequestinfo',
            name='status',
            field=models.CharField(choices=[('COMFIRM', 'COMFIRM'), ('COMPLETE', 'COMPLETE'), ('OPEN', 'OPEN')], default='OPEN', max_length=20),
        ),
    ]
