# Generated by Django 4.1.5 on 2023-02-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_driverinfo_cartype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='carType',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Crossover', 'Crossover'), ('Minivan', 'Minivan')], default='SUV', max_length=20),
        ),
    ]
